export {Alumno} from "./Alumno"
export {Usuario} from "./Usuario"
export {AlumnoUsuario} from "./AlumnoUsuario"
export {Curso} from "./Curso"
export {Docente} from "./Docente"
export {DocenteCurso} from "./DocenteCurso"
